name: Formula CI

on:
  pull_request:
    paths:
      - "Formula/**"
      - ".github/workflows/formula.yml"

jobs:
  conclusion:
    name: conclusion
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Result
        run: ${{ true }}